$(document).ready(function(){
  $(".MYclickshow").click(function(){
    $(".YJshow").hide();
	$(".MYclickhide").show();
	$(".MYclickshow").hide();
	$(".YJhide").show();
  });
  $(".MYclickhide").click(function(){
    $(".YJshow").show();
	$(".MYclickhide").hide();
	$(".MYclickshow").show();
	$(".YJhide").hide();
  });
  $(".MYclickshow01").click(function(){
    $(".YJshow01").hide();
	$(".MYclickhide01").show();
	$(".MYclickshow01").hide();
	$(".YJhide01").show();
  });
  $(".MYclickhide01").click(function(){
    $(".YJshow01").show();
	$(".MYclickhide01").hide();
	$(".MYclickshow01").show();
	$(".YJhide01").hide();
  });
  $(".MYclickshow02").click(function(){
    $(".YJshow02").hide();
	$(".MYclickhide02").show();
	$(".MYclickshow02").hide();
	$(".YJhide02").show();
  });
  $(".MYclickhide02").click(function(){
    $(".YJshow02").show();
	$(".MYclickhide02").hide();
	$(".MYclickshow02").show();
	$(".YJhide02").hide();
  });
  $(".MYclickshow03").click(function(){
    $(".YJshow03").hide();
	$(".MYclickhide03").show();
	$(".MYclickshow03").hide();
	$(".YJhide03").show();
  });
  $(".MYclickhide03").click(function(){
    $(".YJshow03").show();
	$(".MYclickhide03").hide();
	$(".MYclickshow03").show();
	$(".YJhide03").hide();
  });
  $(".MYclickshow04").click(function(){
    $(".YJshow04").hide();
	$(".MYclickhide04").show();
	$(".MYclickshow04").hide();
	$(".YJhide04").show();
  });
  $(".MYclickhide04").click(function(){
    $(".YJshow04").show();
	$(".MYclickhide04").hide();
	$(".MYclickshow04").show();
	$(".YJhide04").hide();
  });
  $(".MYclickshow05").click(function(){
    $(".YJshow05").hide();
	$(".MYclickhide05").show();
	$(".MYclickshow05").hide();
	$(".YJhide05").show();
  });
  $(".MYclickhide05").click(function(){
    $(".YJshow05").show();
	$(".MYclickhide05").hide();
	$(".MYclickshow05").show();
	$(".YJhide05").hide();
  });
});